### ISSUE TITLE
Generalize output files to a single folder

### ISSUE THREAD

**Issue by CurtisColwell** [icolwell/auto_pbs#18]
Running a variety of .pbs files requires a more general directory structure

**Comment by icolwell** [comment]
Can you explain what you have in mind?
1. What other kinds of pbs jobs are you planning to run?
2. Would a proposed directory structure look something like:
auto_pbs/job_scripts
auto_pbs/jobs/job_1/input/
auto_pbs/jobs/job_2/etc

**Comment by CurtisColwell** [comment]
Basically have only input, output and log directories. Created a pull request fixing this.

**Comment by icolwell** [comment]
Addressed in PR #20
