### ISSUE TITLE
Create Folders

### ISSUE THREAD

**Issue by CurtisColwell** [icolwell/auto_pbs#2]
Add all necessary folders and a test input file.

**Comment by icolwell** [comment]
Just create a file located at "auto_pbs/computations/input/example.inp". Once the user runs that input file, the rest of the folders will be created automatically. 

You will also have to change the paths in the `submit_jobs.bash` to point to the folders in the `auto_pbs` directory.

We will have to remember to create a gitignore file to ignore the generated directories.

**Comment by CurtisColwell** [comment]
Got this figured out, I'll create the pull request and update the README when I am home sometime

**Comment by CurtisColwell** [comment]
Creating a branch to work on this

**Comment by CurtisColwell** [comment]
Added pull request

**Comment by icolwell** [comment]
PR #11 resolved this
