### ISSUE TITLE
Update from PBS to SLURM

### ISSUE THREAD

**Issue by CurtisColwell** [icolwell/auto_pbs#29]
ACISS went down permanently and the new Talapas cluster uses SLURM instead of PBS requiring a translation of the script from one language to the other.

**Comment by icolwell** [comment]
In that case, maybe we should fork or create a whole new repo, this is for PBS jobs and could still be used for PBS jobs.

**Comment by icolwell** [comment]
We decided to fork into a new repo here:
[https://github.com/CurtisColwell/auto_slurm](https://github.com/CurtisColwell/auto_slurm)
