### ISSUE TITLE
Fchk File Creation

### ISSUE THREAD

**Issue by CurtisColwell** [icolwell/auto_pbs#7]
Add chk file formatting

**Comment by icolwell** [comment]
See line [line 58](https://github.com/icolwell/auto_pbs/blob/master/job.pbs#L58) for some code that formats the check files. Would just need to add a section to the teardown to copy it back to the users directory.

**Comment by CurtisColwell** [comment]
Tested the code where it was and seems like it would be easier to put the code after teardown. Creating branch to do this.

**Comment by CurtisColwell** [comment]
Pull request created and proposing repo name change from "auto_pbs" to "autoGauss"

**Comment by icolwell** [comment]
Resolved in PR #13
